### ISSUE TITLE
Doesn't compile on go1.9

### ISSUE THREAD

**Issue by tucnak** [rainbowism/gin-pongo2#2]
I just tried to go-get your library and received the following output:
```
# github.com/rainbowism/gin-pongo2
../src/github.com/rainbowism/gin-pongo2/render.go:47:14: cannot use Pongo literal (type Pongo) as type render.Render in return argument:
	Pongo does not implement render.Render (missing WriteContentType method)
../src/github.com/rainbowism/gin-pongo2/render.go:56:14: cannot use Pongo literal (type Pongo) as type render.Render in return argument:
	Pongo does not implement render.Render (missing WriteContentType method)
```

My Go version is `go1.9rc2`
